### ISSUE TITLE
Modifier utilisateur

### ISSUE THREAD

**Issue by tom8513** [To-Ma-Th/Les-Herbiers#15]
Action réalisable depuis le menu utilisateur (uniquement pour les utilisateurs connectés en tant qu'admin)

⚠️ On ne permet pas la modification de tous les attributs ! Seulement ceux-ci :
- mot de passe
- rôle (dans ["Editeur" ; "Administrateur"])
- type (dans ["Amateur" ; "Professionnel"])

**Comment by RedNeath** [comment]
Accompli dans commit [`f70b1cb`](https://github.com/To-Ma-Th/Les-Herbiers/commit/f70b1cb41dc185cb93803e0df6a1c604cd4fcd24)
